version: '3'
services:
  backend:
    command: bash -c 'npm run dev'
    env_file: ./config/backend.env
    expose:
      - '1337'
    image: node:16
    ports:
      - '1337:1337'
    user: node
    volumes:
      - ./backend:/home/node/app
    working_dir: /home/node/app
  frontend:
    command: bash -c 'npm run dev'
    depends_on:
      - backend
    env_file: ./config/frontend.env
    expose:
      - '3000'
    image: node:16
    ports:
      - '3000:3000'
    user: node
    volumes:
      - ./frontend:/home/node/app
    working_dir: /home/node/app
