version: '3'
services:
  backend:
    command: bash -c 'npm run dev || (npm install && npm run dev)'
    expose:
      - '1337'
    image: node:14
    ports:
      - '1337:1337'
    user: node
    volumes:
      - ./backend:/home/node/app
      - ./config/backend.env:/home/node/app/.env
    working_dir: /home/node/app
  frontend:
    command: bash -c 'npm run dev'
    depends_on:
      - backend
    expose:
      - '3000'
    image: node:14
    ports:
      - '3000:3000'
    user: node
    volumes:
      - ./frontend:/home/node/app
      - ./config/frontend.env:/home/node/app/.env
    working_dir: /home/node/app
