version: '3'
services:
  backend:
    command: bash -c 'npm run build && npm run start'
    environment:
      - NODE_ENV=production
    expose:
      - '1337'
    image: node:14
    ports:
      - '1337:1337'
    user: node
    volumes:
      - ./backend:/home/node/app
      - ./config/backend.env:/home/node/app/.env
    working_dir: /home/node/app
  frontend:
    command: bash -c '/test-endpoint.sh backend 1337 && npm run build && npm run start'
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    expose:
      - '3000'
    image: node:14
    ports:
      - '3000:3000'
    user: node
    volumes:
      - ./frontend:/home/node/app
      - ./config/frontend.env:/home/node/app/.env
      - ./scripts/test-endpoint.sh:/test-endpoint.sh
    working_dir: /home/node/app
  nginx:
    command: bash -c '/test-endpoint.sh backend 1337 && echo "Starting NGiNX..." && nginx -g "daemon off;"'
    depends_on:
      - frontend
    image: nginx
    ports:
      - ${PORT:-9000}:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/test-endpoint.sh:/test-endpoint.sh
