#import "./Media.gql"

fragment GlobalFragment on GlobalEntityResponse {
	data {
		attributes {
			title
			title_prefix
			favicon {
				...MediaFragment
			}
			logo {
				...MediaFragment
			}
		}
	}
}
