#import "./fragments/Media.gql"
#import "./fragments/MenuItem.gql"

# Globals
#import "./fragments/Global.gql"

query PageSlugs($slug: String) {
	page: pageBySlug(slug: $slug) {
		data {
			attributes {
				title
				slug
				sections {
					__typename
					... on ComponentSectionsMedia {
						media {
							...MediaFragment
						}
						credit
					}
					... on ComponentSectionsQuote {
						content
						source
					}
					... on ComponentSectionsWysiwyg {
						content
					}
				}
				parent {
					data {
						attributes {
							...MenuItemFragment
							parent {
								data {
									attributes {
										...MenuItemFragment
									}
								}
							}
						}
					}
				}
			}
		}
	}

	global {
		...GlobalFragment
	}
}
