#import "./fragments/Media.gql"

# Globals
#import "./fragments/Global.gql"

query {
	startpage {
		data {
			attributes {
				title
				sections {
					__typename
					... on ComponentSectionsMedia {
						media {
							...MediaFragment
						}
						credit
					}
					... on ComponentSectionsQuote {
						content
						source
					}
					... on ComponentSectionsWysiwyg {
						content
					}
				}
			}
		}
	}

	global {
		...GlobalFragment
	}
}
